import { AgentConfig, TOOL_DESCRIPTIONS, type AvailableTool } from "../types/agent-config.js";

function toPascalCase(str: string): string {
  return str
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join("");
}

export interface AgentManifest {
  $schema: string;
  name: string;
  displayName: string;
  version: string;
  description: string;
  responsibility: string;
  author: string;
  license: string;
  entryPoint: string;
  handler: string;
  capabilities: {
    permissionLevel: string;
    memoryEnabled: boolean;
    executionEnvironment: string;
    outputFormat: string;
  };
  tools: string[];
  input: {
    required: string[];
    optional: string[];
  };
  output: {
    fields: string[];
  };
  metadata: {
    generatedBy: string;
    generatedAt: string;
    pndAgentsVersion: string;
  };
}

export function generateManifestJson(config: AgentConfig): AgentManifest {
  const className = toPascalCase(config.name) + "Agent";
  
  return {
    $schema: "https://pnd-agents.pandora.net/schemas/manifest.json",
    name: config.name,
    displayName: config.displayName,
    version: "1.0.0",
    description: config.description,
    responsibility: config.responsibility,
    author: "Generated by PND Meta-Agent",
    license: "MIT",
    entryPoint: "agent.py",
    handler: `${config.name}.run`,
    capabilities: {
      permissionLevel: config.permissionLevel,
      memoryEnabled: config.memoryEnabled,
      executionEnvironment: config.executionEnvironment,
      outputFormat: config.outputFormat,
    },
    tools: config.allowedTools,
    input: {
      required: ["task_description"],
      optional: generateOptionalInputs(config),
    },
    output: {
      fields: generateOutputFields(config),
    },
    metadata: {
      generatedBy: "pnd-meta-agent",
      generatedAt: new Date().toISOString(),
      pndAgentsVersion: "1.0.0",
    },
  };
}

function generateOptionalInputs(config: AgentConfig): string[] {
  const inputs: string[] = ["metadata"];
  
  if (config.allowedTools.includes("filesystem_read")) {
    inputs.push("path", "file_patterns");
  }
  
  if (config.allowedTools.includes("test_runner")) {
    inputs.push("test_command", "run_tests");
  }
  
  if (config.allowedTools.includes("coverage_analyzer")) {
    inputs.push("coverage_path");
  }
  
  return inputs;
}

function generateOutputFields(config: AgentConfig): string[] {
  const fields: string[] = ["status", "recommendations"];
  
  if (config.allowedTools.includes("filesystem_read")) {
    fields.push("files_analyzed");
  }
  
  if (config.allowedTools.includes("test_runner")) {
    fields.push("test_results");
  }
  
  if (config.allowedTools.includes("coverage_analyzer")) {
    fields.push("coverage");
  }
  
  if (config.outputFormat === "report" || config.outputFormat === "markdown") {
    fields.push("report");
  }
  
  return fields;
}
