import { AgentConfig, TOOL_DESCRIPTIONS, type AvailableTool } from "../types/agent-config.js";

function toPascalCase(str: string): string {
  return str
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join("");
}

export function generateReadme(config: AgentConfig): string {
  const className = toPascalCase(config.name) + "Agent";
  const isReadOnly = config.permissionLevel === "read_only";
  
  const toolsList = config.allowedTools
    .map((tool) => {
      const info = TOOL_DESCRIPTIONS[tool];
      return `- **${tool}**: ${info.description} ${info.readOnly ? "(read-only)" : "(read-write)"}`;
    })
    .join("\n");
  
  return `# ${config.displayName}

${config.description}

## Overview

**Responsibility**: ${config.responsibility}

**Permission Level**: ${config.permissionLevel.toUpperCase()} ${isReadOnly ? "(This agent cannot modify any files or state)" : ""}

**Execution Environment**: ${config.executionEnvironment}

**Memory**: ${config.memoryEnabled ? "Enabled" : "Disabled"}

**Output Format**: ${config.outputFormat}

## Installation

This agent is part of the pnd-agents system. To use it:

1. Copy the agent directory to \`src/agents/\` in your pnd-agents installation
2. Register the agent in \`src/agents/__init__.py\`
3. Add the agent handler to \`workflows/agent_dispatcher.py\`

## Usage

### As a Standalone Agent

\`\`\`python
from ${config.name} import ${className}

agent = ${className}()
result = agent.run({
    "task_description": "Your task description here",
    "input_data": {
        # Input data specific to your task
    },
    "metadata": {
        # Optional metadata
    }
})

print(result.to_dict())
\`\`\`

### In a Workflow

\`\`\`python
from workflows.agent_dispatcher import AgentDispatcher

dispatcher = AgentDispatcher()
dispatcher.register("${config.name}", ${config.name}_handler)

result = dispatcher.execute("${config.name}", {
    "task": "Your task description",
    "input": {},
    "metadata": {}
})
\`\`\`

## Tools

This agent has access to the following tools:

${toolsList}

## Configuration

The agent can be configured using the \`${className}Config\` class:

\`\`\`python
from ${config.name} import ${className}, ${className}Config

config = ${className}Config(
    ${generateConfigExample(config)}
)

agent = ${className}(config=config)
\`\`\`

## Input Schema

| Field | Type | Required | Description |
|-------|------|----------|-------------|
| task_description | string | Yes | Description of the task to perform |
| input_data | object | No | Additional input data |
| metadata | object | No | Metadata for the task |

## Output Schema

| Field | Type | Description |
|-------|------|-------------|
| status | string | "success", "error", or "partial" |
| data | object | Result data from the agent |
| recommendations | array | List of recommendations |
| error | string | Error message if status is "error" |

## Permissions

This agent operates under the following permission constraints:

${generatePermissionsSection(config)}

## Generated By

This agent was generated by the **PND Meta-Agent** (Mastra-based Agent Factory).

- Generated at: ${new Date().toISOString()}
- pnd-agents version: 1.0.0

## License

MIT License - See LICENSE file for details.
`;
}

function generateConfigExample(config: AgentConfig): string {
  const lines: string[] = [];
  
  if (config.outputFormat === "report" || config.outputFormat === "markdown") {
    lines.push(`output_format="${config.outputFormat}",`);
  }
  
  if (config.memoryEnabled) {
    lines.push('memory_enabled=True,');
  }
  
  if (config.allowedTools.includes("test_runner")) {
    lines.push('test_command="npm test",');
  }
  
  if (config.allowedTools.includes("filesystem_read")) {
    lines.push('root_path=".",');
  }
  
  if (lines.length === 0) {
    return "# Default configuration";
  }
  
  return lines.join("\n    ");
}

function generatePermissionsSection(config: AgentConfig): string {
  const isReadOnly = config.permissionLevel === "read_only";
  const lines: string[] = [];
  
  if (isReadOnly) {
    lines.push("- **Read-Only Mode**: This agent cannot modify files, execute write commands, or change state");
    lines.push("- **Allowed Operations**: Read files, analyze code, run tests (read output only)");
    lines.push("- **Denied Operations**: Write files, execute shell commands, modify git");
  } else {
    lines.push("- **Read-Write Mode**: This agent can modify files and execute commands");
    lines.push("- **Caution**: Review all changes before committing");
  }
  
  lines.push("");
  lines.push("### Runtime Enforcement");
  lines.push("");
  lines.push("- All operations are validated before execution");
  lines.push("- All operations are logged for audit purposes");
  lines.push("- Permission violations will cause the agent to fail immediately");
  
  return lines.join("\n");
}
